name: Publish DNS zones
on:
  push:
    branches:
      - live
jobs:
  publish:
    name: Publish sibr.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GANDI_PAT: ${{ secrets.GANDI_PAT }}
        run: bin/gandi.sh sibr.dev
